### ISSUE TITLE
Update Footer Social Links

### ISSUE THREAD

**Issue by davidtaing** [codesydney/lloydconsulting#24]
Update the social links in the Navbar so that they direct the user to Dean's social media pages.

I think it would be better if the links open in new tabs. See here for more information: https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/

Note: I'll need to check if Lloyd has a Twitter or Facebook account.

## Tasks
- [x] Update Footer Facebook Link
- [x] Update Footer LinkedIn Link
- [x] Update Footer Instagram Link
- [x] Update Footer Twitter Link

Note: I won't turn these into issues for now, but feel free to open an issue if you would like to work on these.

## Related
- #19
